-- MySQL Script generated by MySQL Workbench
-- Sat Jan  2 14:24:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`listaspesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`listaspesa` (
  `idlistaspesa` INT NOT NULL,
  PRIMARY KEY (`idlistaspesa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Utenti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Utenti` (
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `listaspesa_idlistaspesa` INT NOT NULL,
  PRIMARY KEY (`email`, `listaspesa_idlistaspesa`),
  INDEX `fk_Utenti_listaspesa1_idx` (`listaspesa_idlistaspesa` ASC) VISIBLE,
  CONSTRAINT `fk_Utenti_listaspesa1`
    FOREIGN KEY (`listaspesa_idlistaspesa`)
    REFERENCES `mydb`.`listaspesa` (`idlistaspesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ricetta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ricetta` (
  `idRicetta` INT NOT NULL,
  `preparazione` VARCHAR(100) NULL,
  `note` VARCHAR(100) NULL,
  `idAutore` VARCHAR(45) NOT NULL,
  `idAttrezzo` VARCHAR(45) NOT NULL,
  `idProdotto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRicetta`),
  INDEX `email_idx` (`idAutore` ASC) VISIBLE,
  CONSTRAINT `email`
    FOREIGN KEY (`idAutore`)
    REFERENCES `mydb`.`Utenti` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attrezzo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attrezzo` (
  `idAttrezzo` INT NOT NULL,
  `capacita` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `Utenti_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAttrezzo`),
  INDEX `fk_attrezzo_Utenti1_idx` (`Utenti_email` ASC) VISIBLE,
  CONSTRAINT `fk_attrezzo_Utenti1`
    FOREIGN KEY (`Utenti_email`)
    REFERENCES `mydb`.`Utenti` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prodotto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prodotto` (
  `proprietario` VARCHAR(45) NOT NULL,
  `nomeProd` VARCHAR(45) NOT NULL,
  `quantita` VARCHAR(45) NOT NULL,
  `idProdotto` INT NOT NULL,
  INDEX `email_idx` (`proprietario` ASC) VISIBLE,
  PRIMARY KEY (`idProdotto`),
  CONSTRAINT `email`
    FOREIGN KEY (`proprietario`)
    REFERENCES `mydb`.`Utenti` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prodotto_has_ricetta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prodotto_has_ricetta` (
  `prodotto_idProdotto` INT NOT NULL,
  `ricetta_idRicetta` INT NOT NULL,
  `quantitaUtilizzata` INT NULL,
  PRIMARY KEY (`prodotto_idProdotto`, `ricetta_idRicetta`),
  INDEX `fk_prodotto_has_ricetta_ricetta1_idx` (`ricetta_idRicetta` ASC) VISIBLE,
  INDEX `fk_prodotto_has_ricetta_prodotto1_idx` (`prodotto_idProdotto` ASC) VISIBLE,
  CONSTRAINT `fk_prodotto_has_ricetta_prodotto1`
    FOREIGN KEY (`prodotto_idProdotto`)
    REFERENCES `mydb`.`prodotto` (`idProdotto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prodotto_has_ricetta_ricetta1`
    FOREIGN KEY (`ricetta_idRicetta`)
    REFERENCES `mydb`.`ricetta` (`idRicetta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attrezzo_has_ricetta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attrezzo_has_ricetta` (
  `attrezzo_idAttrezzo` INT NOT NULL,
  `ricetta_idRicetta` INT NOT NULL,
  PRIMARY KEY (`attrezzo_idAttrezzo`, `ricetta_idRicetta`),
  INDEX `fk_attrezzo_has_ricetta_ricetta1_idx` (`ricetta_idRicetta` ASC) VISIBLE,
  INDEX `fk_attrezzo_has_ricetta_attrezzo1_idx` (`attrezzo_idAttrezzo` ASC) VISIBLE,
  CONSTRAINT `fk_attrezzo_has_ricetta_attrezzo1`
    FOREIGN KEY (`attrezzo_idAttrezzo`)
    REFERENCES `mydb`.`attrezzo` (`idAttrezzo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attrezzo_has_ricetta_ricetta1`
    FOREIGN KEY (`ricetta_idRicetta`)
    REFERENCES `mydb`.`ricetta` (`idRicetta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prodotto_has_listaspesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prodotto_has_listaspesa` (
  `prodotto_idProdotto` INT NOT NULL,
  `listaspesa_idlistaspesa` INT NOT NULL,
  `quantitaMancante` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`prodotto_idProdotto`, `listaspesa_idlistaspesa`),
  INDEX `fk_prodotto_has_listaspesa_listaspesa1_idx` (`listaspesa_idlistaspesa` ASC) VISIBLE,
  INDEX `fk_prodotto_has_listaspesa_prodotto1_idx` (`prodotto_idProdotto` ASC) VISIBLE,
  CONSTRAINT `fk_prodotto_has_listaspesa_prodotto1`
    FOREIGN KEY (`prodotto_idProdotto`)
    REFERENCES `mydb`.`prodotto` (`idProdotto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prodotto_has_listaspesa_listaspesa1`
    FOREIGN KEY (`listaspesa_idlistaspesa`)
    REFERENCES `mydb`.`listaspesa` (`idlistaspesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
